// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsNZw8MjibqfzINY7ZL0irkfNweIkNJOU',
    appId: '1:190658220808:web:12219c825edbc3928c12bd',
    messagingSenderId: '190658220808',
    projectId: 'soz-jangi',
    authDomain: 'soz-jangi.firebaseapp.com',
    storageBucket: 'soz-jangi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJM_Cp4RjL-lFb6as1Psl-cvx61ZBGks',
    appId: '1:190658220808:android:6792f82bb432aa2e8c12bd',
    messagingSenderId: '190658220808',
    projectId: 'soz-jangi',
    storageBucket: 'soz-jangi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-OuBFhGE5ce0MRCHSOJmQkFaId0FRMKg',
    appId: '1:190658220808:ios:646ed842a3dfaad18c12bd',
    messagingSenderId: '190658220808',
    projectId: 'soz-jangi',
    storageBucket: 'soz-jangi.firebasestorage.app',
    iosBundleId: 'uz.sozjangi.app',
  );
}
