#!/usr/bin/env python3
"""Turn a generated schedule.json into a Supabase seed for `daily_puzzles`.

Always writes an idempotent SQL file (safe to re-run; upserts on the date PK).
If SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY are set, it can also push the rows
straight to the project via the PostgREST endpoint (service role bypasses RLS).

Usage:
  python3 seed_from_schedule.py \
      --schedule ../../tool/generator/out/schedule.json \
      --out ./seed_daily_puzzles.sql          # write SQL only
  python3 seed_from_schedule.py --schedule ... --push   # also upload via REST
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys


def sql_escape(s):
    return s.replace("'", "''")


def to_sql(puzzles):
    lines = [
        "-- Generated by seed_from_schedule.py — idempotent upsert.",
        "insert into public.daily_puzzles (date, word, definition_uz, difficulty) values",
    ]
    rows = []
    for p in puzzles:
        d = sql_escape(p["date"])
        w = sql_escape(p["word"])
        defn = "null" if p.get("definition_uz") in (None, "") else f"'{sql_escape(p['definition_uz'])}'"
        rows.append(f"  ('{d}', '{w}', {defn}, {int(p['difficulty'])})")
    lines.append(",\n".join(rows))
    lines.append(
        "on conflict (date) do update set\n"
        "  word = excluded.word,\n"
        "  definition_uz = excluded.definition_uz,\n"
        "  difficulty = excluded.difficulty;"
    )
    return "\n".join(lines) + "\n"


def push_rest(puzzles):
    url = os.environ["SUPABASE_URL"].rstrip("/")
    key = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
    payload = json.dumps([
        {"date": p["date"], "word": p["word"],
         "definition_uz": p.get("definition_uz"), "difficulty": int(p["difficulty"])}
        for p in puzzles
    ])
    endpoint = f"{url}/rest/v1/daily_puzzles?on_conflict=date"
    cmd = [
        "curl", "-sS", "-X", "POST", endpoint,
        "-H", f"apikey: {key}",
        "-H", f"Authorization: Bearer {key}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: resolution=merge-duplicates,return=minimal",
        "--data-binary", "@-",
    ]
    res = subprocess.run(cmd, input=payload, capture_output=True, text=True)
    if res.returncode != 0 or (res.stdout and "message" in res.stdout):
        print("push failed:", res.stdout or res.stderr, file=sys.stderr)
        return False
    print(f"pushed {len(puzzles)} rows to {endpoint}")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--schedule", required=True)
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "seed_daily_puzzles.sql"))
    ap.add_argument("--push", action="store_true", help="also upload via Supabase REST")
    args = ap.parse_args()

    with open(args.schedule, encoding="utf-8") as f:
        puzzles = json.load(f)["puzzles"]

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(to_sql(puzzles))
    print(f"wrote {len(puzzles)} rows -> {args.out}")

    if args.push:
        if not (os.environ.get("SUPABASE_URL") and os.environ.get("SUPABASE_SERVICE_ROLE_KEY")):
            print("--push set but SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY missing", file=sys.stderr)
            return 1
        return 0 if push_rest(puzzles) else 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
