#!/usr/bin/env python3
"""Turn a generated schedule.json into a Supabase seed for `daily_puzzles`.

Targets the NORMALISED live schema (see supabase/migrations):

    words(id, word, normalized_word = upper(word), length, tier, theme,
          is_answer_candidate, ...)
    daily_puzzles(id, puzzle_number UNIQUE, puzzle_date UNIQUE,
                  word_id -> words.id, theme_override, ...)

The answer never lives on `daily_puzzles` directly — it references a row in
`words` by id. So this seed resolves each scheduled word to its `words.id` by
`normalized_word = upper(word)` and inserts the FK. It is therefore a hard
prerequisite that the dictionary is already loaded (tool/corpus/output/
words_import.sql) — every scheduled word must exist in `words`, or its day is
skipped (the seed prints a warning and a post-check in the deploy runbook
asserts the row count).

Definitions/themes are intentionally NOT seeded here: they live on the `words`
row (words_import.sql carries theme + definition_uz for every answer, WS-B) and
reach clients via the daily_puzzle_public view; the bundled schedule duplicates
them for the offline fallback. `difficulty`/tier also isn't stored per-puzzle
here; it lives on the `words` row.

Idempotent: `on conflict (puzzle_date) do update` re-points a date to the newly
scheduled word, so re-running to correct/extend the schedule is safe.

Usage:
  python3 seed_from_schedule.py \
      --schedule ../../tool/generator/out/schedule.json \
      --out ./seed_daily_puzzles.sql
"""

from __future__ import annotations

import argparse
import json
import os


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def to_sql(puzzles: list[dict]) -> str:
    values = []
    for p in puzzles:
        pn = int(p["puzzle_number"])
        date = sql_escape(p["date"])
        norm = sql_escape(p["word"].upper())
        values.append(f"    ({pn}, '{date}'::date, '{norm}')")

    return (
        "-- Generated by seed_from_schedule.py — idempotent, normalised schema.\n"
        "-- Prerequisite: words must already be loaded "
        "(tool/corpus/output/words_import.sql).\n"
        "-- Resolves each scheduled word to words.id via normalized_word = upper(word).\n"
        "with scheduled (puzzle_number, puzzle_date, normalized_word) as (\n"
        "  values\n" + ",\n".join(values) + "\n"
        ")\n"
        "insert into public.daily_puzzles (puzzle_number, puzzle_date, word_id)\n"
        "select s.puzzle_number, s.puzzle_date, w.id\n"
        "from scheduled s\n"
        "join public.words w on w.normalized_word = s.normalized_word\n"
        "on conflict (puzzle_date) do update\n"
        "  set puzzle_number = excluded.puzzle_number,\n"
        "      word_id       = excluded.word_id;\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--schedule", required=True)
    ap.add_argument(
        "--out",
        default=os.path.join(os.path.dirname(__file__), "seed_daily_puzzles.sql"),
    )
    args = ap.parse_args()

    with open(args.schedule, encoding="utf-8") as f:
        puzzles = json.load(f)["puzzles"]

    for p in puzzles:
        if "puzzle_number" not in p:
            raise SystemExit(
                "schedule.json lacks puzzle_number — regenerate with a "
                "generate_schedule.py that emits it (--start-number)."
            )

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(to_sql(puzzles))
    print(
        f"wrote {len(puzzles)} daily_puzzles rows "
        f"({puzzles[0]['date']} #{puzzles[0]['puzzle_number']} .. "
        f"{puzzles[-1]['date']} #{puzzles[-1]['puzzle_number']}) -> {args.out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
