#!/usr/bin/env python3
"""Export the built corpus to a SQL import for the live Supabase `words` table.

Practice mode already loads its words from the corpus build (`out/`, bundled
into the app as gzipped assets). Daily mode's `words` table is a separate,
manually-populated store that must never diverge from the same curated corpus
— this script is the one bridge between the two so that never happens again.

Input : out/answers_tiered.tsv (curated, tail-dropped answer pool + tier)
         out/valid_guesses.txt  (superset accepted-guess list)
Output: output/words_import.sql — batched, idempotent INSERTs matching the
         live `words` schema exactly: (word, length, tier, theme,
         is_answer_candidate). `theme` is left NULL everywhere (full-corpus
         theming is separate future work); `tier` is the Uzbek difficulty
         label for answers ("oson"/"oʻrta"/"qiyin") and the table's own
         "standart" default for every other accepted guess.

ON CONFLICT (word) DO NOTHING makes re-running this after a future corpus
rebuild (e.g. a new suffix fix) safe: existing rows — including anything
curated by hand directly in Supabase — are never touched or duplicated.

Usage:
  python3 export_supabase.py                    # out/ -> output/words_import.sql
  python3 export_supabase.py --out other_dir --sql-out other.sql
"""

from __future__ import annotations

import argparse
import os

import uz_letters as U

HERE = os.path.dirname(os.path.abspath(__file__))

BATCH_SIZE = 500

# Corpus tier (1=easy..3=hard, see assign_tiers) -> the Uzbek-language label
# the `words.tier` column actually stores (verified against the live table's
# seed row and assets/translations/uz.json's tier_easy/medium/hard strings).
TIER_LABELS = {1: "oson", 2: "oʻrta", 3: "qiyin"}
NON_ANSWER_TIER = "standart"  # matches the column's own DB default


def load_answer_tiers(path):
    """Return {word: tier_label} from answers_tiered.tsv (word\ttier\tfreq)."""
    tiers = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            word, tier, _freq = line.split("\t")
            tiers[word] = TIER_LABELS[int(tier)]
    return tiers


def load_valid_guesses(path):
    with open(path, encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]


def sql_literal(word):
    """Single-quote a word for SQL. Game words are letters + U+02BB only (see
    uz_letters.tokenize) — never a literal apostrophe — so no escaping is
    actually reachable; the replace is defense-in-depth, not a live path."""
    return "'" + word.replace("'", "''") + "'"


def build_rows(answer_tiers, valid_guesses):
    rows = []
    for word in valid_guesses:
        length = U.logical_len(word)
        is_answer = word in answer_tiers
        tier = answer_tiers[word] if is_answer else NON_ANSWER_TIER
        rows.append((word.upper(), length, tier, is_answer))
    return rows


def write_sql(rows, sql_out):
    os.makedirs(os.path.dirname(sql_out), exist_ok=True)
    with open(sql_out, "w", encoding="utf-8") as f:
        f.write(
            "-- So'z Jangi — words table import, generated by "
            "tool/corpus/export_supabase.py\n"
            "-- Source of truth: tool/corpus/out/{answers_tiered.tsv,valid_guesses.txt}\n"
            "-- Practice mode's local dictionary and Daily's `words` table must never\n"
            "-- diverge again — always regenerate this file from the same corpus build\n"
            "-- rather than hand-editing either side.\n"
            "-- Safe to re-run: ON CONFLICT (word) DO NOTHING never touches existing rows.\n\n"
        )
        for i in range(0, len(rows), BATCH_SIZE):
            batch = rows[i : i + BATCH_SIZE]
            f.write(
                "INSERT INTO public.words (word, length, tier, theme, "
                "is_answer_candidate)\nVALUES\n"
            )
            values = [
                f"  ({sql_literal(word)}, {length}, {sql_literal(tier)}, "
                f"NULL, {'true' if is_answer else 'false'})"
                for word, length, tier, is_answer in batch
            ]
            f.write(",\n".join(values))
            f.write("\nON CONFLICT (word) DO NOTHING;\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(HERE, "out"))
    ap.add_argument(
        "--sql-out", default=os.path.join(HERE, "output", "words_import.sql")
    )
    args = ap.parse_args()

    answer_tiers = load_answer_tiers(os.path.join(args.out, "answers_tiered.tsv"))
    valid_guesses = load_valid_guesses(os.path.join(args.out, "valid_guesses.txt"))
    assert set(answer_tiers) <= set(valid_guesses), (
        "every answer must also be a valid guess"
    )

    rows = build_rows(answer_tiers, valid_guesses)
    write_sql(rows, args.sql_out)

    answer_rows = sum(1 for _, _, _, is_answer in rows if is_answer)
    print(
        f"wrote {len(rows)} rows ({answer_rows} answer candidates, "
        f"{len(rows) - answer_rows} guess-only) -> {args.sql_out}"
    )


if __name__ == "__main__":
    main()
